### ISSUE TITLE
asset-manifest.json

### ISSUE THREAD

**Issue by mavickers** [johnmichel/Library-Detector-for-Chrome#158]
Every page loaded in Chrome with this extension enabled is now showing a 404'd request on /asset-manifest.json.

Attached is a screenshot from this very page.

This may be related - I'm no longer to login to Atlassian sites (via id.atlassian.com) unless this extension is disabled.

![image](https://user-images.githubusercontent.com/17083013/71989257-5292df00-31ff-11ea-946a-a6a38d1af46a.png)

**Comment by mavickers** [comment]
PS - running 5.6.0 of the plugin.

**Comment by johnmichel** [comment]
@mavickers Thanks for this report.

@housseindjirdeh Do you have any ideas for the best way to mitigate this with respect to the `Create React App` detection?

**Comment by DavidUrting** [comment]
We have the same issue when using the 'lighthouse' package to automatically test our web pages for web accessibility. The automated test run hangs due to a login popup that appears since the asset-manifest.json is fetched from the domain root (/) and not relatively from the application location (/some/application).

I guess (not sure) that this line:
`const response = await fetch('/asset-manifest.json');`
should be:
`const response = await fetch('asset-manifest.json');`
