### ISSUE TITLE
Wrong react detection algoritm

### ISSUE THREAD

**Issue by FDiskas** [johnmichel/Library-Detector-for-Chrome#94]
For example spotify web player is made with react. I't not detects this.
Open DEV tools and type:
```js
document.querySelector('[data-reactroot], [data-reactid]');
```
Please update the detection.
But you should probably wait for some time for ex.
```js
var selector = '[data-reactroot], [data-reactid]';
function checkForReact() {
    var runningReact = !!document.querySelector(selector);
    if (runningReact) {
        chrome.runtime.sendMessage({
            react: true
        });
    } else {
        // React isn't currently present, check again in a second in case it's
        // loaded after the page is initialized.
        setTimeout(checkForReact, 1000);
    }
}
```

**Comment by johnmichel** [comment]
Thank you for the report about this.

Unfortunately, this is something that won't be addressed as Spotify has taken steps to obscure what libraries are in use for its web player so that the `React` object isn't available on `window`.  Checking for `DOM` attributes is not something this extension is going to support in the near-term as it would only serve to increase detection time and introduce more potential false positives.

**Comment by FDiskas** [comment]
Check this www.tlate.com https://github.com/FDiskas/tlate
And there is nothing​ special done about hiding react. If react script is loaded with npm and then transpiled (usually all normal websites are done me that) it wouldn't be visible by your detection script. And it wouldn't be possible to get the real version

**Comment by johnmichel** [comment]
> If react script is loaded with npm and then transpiled (usually all normal websites are done me that) it wouldn't be visible by your detection script.

While valid, I'm still not interested in using `DOM` attributes as a way to detect libraries.  The delay in waiting for the libraries to initialize themselves and add the values would serve to further delay detection.  I'm going to stick with `window`-based detection for the time being.  Sorry about that.
